class Language {
  #code: string;
  #name: string;
  #nativeName: string;

  constructor(code: string, name: string, nativeName: string) {
    this.#code = code;
    this.#name = name;
    this.#nativeName = nativeName;
  }

  public get code() {
    return this.#code;
  }

  public get name() {
    return this.#name;
  }

  public get nativeName() {
    return this.#nativeName;
  }

  public get label() {
    return `${this.#name} (${this.#nativeName})`;
  }
}

export const worldLanguages: Language[] = [
  new Language('eng', 'English', 'English'),
  new Language('cmn', 'Mandarin Chinese', '普通话'),
  new Language('hin', 'Hindi', 'मानक हिन्दी'),
  new Language('spa', 'Spanish', 'español'),
  new Language('arb', 'Standard Arabic', 'العربية'),
  new Language('fra', 'French', 'français'),
  new Language('ben', 'Bengali', 'বাংলা'),
  new Language('por', 'Portuguese', 'Português'),
  new Language('rus', 'Russian', 'русский язык‎'),
  new Language('urd', 'Urdu', 'اُردُو'),
  new Language('ind', 'Indonesian', 'Bahasa Indonesia'),
  new Language('deu', 'Standard German', 'Deutsch'),
  new Language('jpn', 'Japanese', '日本語‎'),
  new Language('pcm', 'Nigerian Pidgin', 'Naijá'),
  new Language('arz', 'Egyptian Arabic', 'مصري'),
  new Language('mar', 'Marathi', 'मराठी'),
  new Language('tel', 'Telugu', 'తెలుగు'),
  new Language('tur', 'Turkish', 'Türkçe'),
  new Language('hau', 'Hausa', 'Hausa'),
  new Language('tam', 'Tamil', 'தமிழ்'),
  new Language('yue', 'Yue Chinese', '粵語'),
  new Language('swh', 'Swahili', 'Kiswahili'),
  new Language('vie', 'Vietnamese', 'Tiếng Việt'),
  new Language('wuu', 'Wu Chinese', '江南话'),
  new Language('tgl', 'Tagalog', 'Tagalog'),
  new Language('pnb', 'Western Punjabi', 'پنجابی'),
  new Language('kor', 'Korean', '한국말'),
  new Language('pes', 'Iranian Persian', 'فارسی'),
  new Language('jav', 'Javanese', 'Jawa'),
  new Language('ita', 'Italian', 'Italiano'),
  new Language('guj', 'Gujarati', 'ગુજરાત'),
  new Language('tha', 'Thai', 'ภาษาไทย'),
  new Language('amh', 'Amharic', 'ኣማርኛ'),
  new Language('kan', 'Kannada', 'ಕನ್ನಡ'),
  new Language('apc', 'Levantine Arabic', 'شامي'),
  new Language('bho', 'Bhojpuri', 'भोजपुरी'),
  new Language('nan', 'Min Nan Chinese', '闽南语'),
  new Language('apd', 'Sudanese Arabic', 'سوداني'),
  new Language('cjy', 'Jinyu Chinese', '晋语'),
  new Language('yor', 'Yoruba', 'Èdè Yorùbá'),
  new Language('hak', 'Hakka Chinese', '客家話‎'),
  new Language('mya', 'Burmese', 'မြန်မာစကား'),
  new Language('pol', 'Polish', 'język polski‎'),
  new Language('arq', 'Algerian Arabic', 'العامية'),
  new Language('lin', 'Lingala', 'Lingala'),
  new Language('ory', 'Odia', 'ଓଡ଼ିଆ'),
  new Language('ary', 'Moroccan Arabic', 'الدارجة'),
  new Language('ukr', 'Ukrainian', 'українська мова‎'),
  new Language('hsn', 'Xiang Chinese', '湘语'),
  new Language('mal', 'Malayalam', 'മലയാളം'),
  new Language('pan', 'Eastern Punjabi', 'ਪੰਜਾਬੀ ਭਾਸ਼ਾ‎'),
  new Language('snd', 'Sindhi', 'سنڌي'),
  new Language('sun', 'Sunda', 'Basa Sunda'),
  new Language('npi', 'Nepali', 'नेपाली'),
  new Language('prs', 'Dari', 'دری'),
  new Language('ibo', 'Igbo', 'Asụsụ Igbo'),
  new Language('uzn', 'Northern Uzbek', 'ўзбек тили'),
  new Language('zul', 'Zulu', 'isiZulu'),
  new Language('skr', 'Saraiki', 'سرائیکی'),
  new Language('nld', 'Dutch', 'Nederlands'),
  new Language('ron', 'Romanian', 'Limba română'),
  new Language('aec', "Sa'idi Arabic", 'صعيدى'),
  new Language('gaz', 'West Central Oromo', 'Afaan Oromoo'),
  new Language('pbu', 'Northern Pashto', 'پښتو'),
  new Language('som', 'Somali', 'Af-Soomaali'),
  new Language('wol', 'Wolof', 'Wolof làkk'),
  new Language('gan', 'Gan Chinese', '江西話'),
  new Language('mai', 'Maithili', 'मैथिली'),
  new Language('mag', 'Magahi', 'मगही'),
  new Language('xho', 'Xhosa', 'isiXhosa'),
  new Language('zlm', 'Malay', 'Bahasa Melayu'),
  new Language('ars', 'Najdi Arabic', 'نجدي'),
  new Language('pbt', 'Southern Pashto', 'پښتو'),
  new Language('afr', 'Afrikaans', 'Afrikaans'),
  new Language('sin', 'Sinhala', 'සිංහල'),
  new Language('khm', 'Khmer', 'ខ្មែរ‎'),
  new Language('acm', 'Mesopotamian Arabic', 'اللهجة العراقية'),
  new Language('fuv', 'Nigerian Fulfulde', 'Fulfulde'),
  new Language('kaz', 'Kazakh', 'казақ тілі'),
  new Language('kmr', 'Northern Kurdish', 'Kurmancî'),
  new Language('hne', 'Chhattisgarhi', 'छत्तीसगढ़ी'),
  new Language('ceb', 'Cebuano', 'Binisaya'),
  new Language('asm', 'Assamese', 'অসমীয়া'),
  new Language('tts', 'Northeastern Thai', 'อีสาน‎'),
  new Language('kin', 'Kinyarwanda', 'Ikinyarwanda'),
  new Language('bar', 'Bavarian', 'Boarisch'),
  new Language('nya', 'Chichewa', 'Chicheŵa'),
  new Language('bam', 'Bamanankan', 'Bamanankan'),
  new Language('tsn', 'Setswana', 'Setswana'),
  new Language('nso', 'Northern Sotho', 'Sesotho sa Leboa'),
  new Language('sot', 'Southern Sotho', 'Sesotho'),
  new Language('swe', 'Swedish', 'Svenska'),
  new Language('hat', 'Haitian Creole', 'Kreyòl Ayisyen'),
  new Language('ell', 'Greek', 'Νέα Ελληνικά'),
  new Language('run', 'Rundi', 'Ikirundi'),
  new Language('ctg', 'Chittagonian', 'চাঁটগাঁইয়া বুলি'),
  new Language('dyu', 'Jula', 'Julakan'),
  new Language('dcc', 'Deccan', 'دکھنی'),
  new Language('vjk', 'Bajjika', 'बज्जिका'),
  new Language('ayn', 'Sanaani Arabic', 'يمني'),
  new Language('hun', 'Hungarian', 'Magyar'),
  new Language('ktu', 'Kituba', 'Kikongo ya Leta'),
  new Language('ces', 'Czech', 'Čeština'),
  new Language('acq', "Ta'izzi-Adeni Arabic", 'لهجة تعزية عدنية'),
  new Language('sck', 'Sadri', 'सादरी'),
  new Language('aeb', 'Tunisian Arabic', 'تونسي'),
  new Language('wes', 'Cameroon Pidgin', 'Pidgin'),
  new Language('mos', 'Moore', 'Moore'),
  new Language('azb', 'South Azerbaijani', 'آذربایجانجا'),
  new Language('mnp', 'Min Bei Chinese', '閩北語'),
  new Language('syl', 'Sylheti', 'ꠍꠤꠟꠐꠤ'),
  new Language('lug', 'Ganda', 'Luganda'),
  new Language('swc', 'Congo Swahili', 'Kiswahili'),
  new Language('hae', 'Eastern Oromo', 'Afaan Oromoo'),
  new Language('cdo', 'Min Dong Chinese', '闽东话'),
  new Language('afb', 'Gulf Arabic', 'خليجي'),
  new Language('sna', 'Shona', 'ChiShona'),
  new Language('acw', 'Hijazi Arabic', 'حجازي'),
  new Language('ibb', 'Ibibio', 'Ibibio'),
  new Language('rkt', 'Rangpuri', 'রংপুরী'),
  new Language('uig', 'Uyghur', 'ئۇيغۇر تىلى'),
  new Language('ayp', 'North Mesopotamian Arabic', 'مصلاوي'),
  new Language('azj', 'North Azerbaijani', 'Azərbaycan dili'),
  new Language('srp', 'Serbian', 'српски'),
  new Language('tso', 'Tsonga', 'Xitsonga'),
  new Language('tgk', 'Tajik', 'тоҷикӣ'),
  new Language('aka', 'Akan', 'Akan'),
  new Language('tir', 'Tigrigna', 'ትግርኛ'),
  new Language('bgc', 'Haryanvi', 'हरियाणवी'),
  new Language('gax', 'Borana-Arsi-Guji Oromo', 'Afaan Oromoo'),
  new Language('heb', 'Hebrew', 'עברית'),
  new Language('cat', 'Catalan', 'Català'),
  new Language('knc', 'Yerwa Kanuri', 'Yerwa Kanuri'),
  new Language('kik', 'Gikuyu', 'Gĩgĩkũyũ'),
  new Language('suk', 'Sukuma', 'Kisukuma'),
  new Language('kng', 'Koongo', 'Kikongo'),
  new Language('bul', 'Bulgarian', 'български език‎'),
  new Language('kab', 'Kabyle', 'ⵜⴰⵇⴱⴰⵢⵍⵉⵜ'),
  new Language('rwr', 'Marwari', 'मारवाड़ी'),
  new Language('umb', 'Umbundu', 'Umbundu'),
  new Language('mad', 'Madura', 'Basa Mathura'),
  new Language('kri', 'Krio', 'Krio'),
  new Language('sat', 'Santhali', 'Har Rar'),
  new Language('plt', 'Merina Malagasy', 'Malagasy ôfisialy'),
  new Language('slk', 'Slovak', 'Slovenčina'),
  new Language('kas', 'Kashmiri', 'کٲشُر'),
  new Language('lua', 'Luba-Kasai', 'Ciluba'),
  new Language('vah', 'Varhadi-Nagpuri', 'वरहदी-नागपुरी'),
  new Language('ins', 'Indian Sign Language', ''),
  new Language('gug', 'Paraguayan Guaraní', "Avañe'ẽ"),
  new Language('ilo', 'Ilocano', 'Ilokano'),
  new Language('gsw', 'Swiss German', 'Schwiizerdütsch'),
  new Language('hrv', 'Croatian', 'Hrvatski'),
  new Language('pst', 'Central Pashto', 'پښتو'),
  new Language('fuc', 'Pulaar', 'Pulaar'),
  new Language('hil', 'Hiligaynon', 'Ilonggo'),
  new Language('tuk', 'Turkmen', 'Türkmençe'),
  new Language('dje', 'Zarma', 'Zarma sanni'),
  new Language('nod', 'Northern Thai', 'คำเมือง'),
  new Language('bjj', 'Kanauji', 'देहाती'),
  new Language('shi', 'Tachelhit', 'ⵜⴰⵛⵍⵃⵉⵢⵜ'),
  new Language('dan', 'Danish', 'Dansk'),
  new Language('fub', 'Adamawa Fulfulde', 'Fulfulde'),
  new Language('nap', 'Napoletano', 'Napulitano'),
  new Language('bns', 'Bundeli', 'बुन्देली'),
  new Language('fin', 'Finnish', 'Suomi'),
  new Language('ayl', 'Libyan Arabic', 'ليبي'),
  new Language('ewe', 'Éwé', 'Èʋegbe'),
  new Language('mup', 'Malvi', 'मालवी'),
  new Language('czh', 'Huizhou Chinese', '徽州話'),
  new Language('nor', 'Norwegian', 'Norsk'),
  new Language('kir', 'Kyrgyz', 'кыргыз тили'),
  new Language('ckb', 'Central Kurdish', 'زمانی سۆرانی‎'),
  new Language('bci', 'Baoulé', 'Wawle'),
  new Language('kam', 'Kamba', 'Kĩkamba'),
  new Language('luo', 'Dholuo', 'Dholuo'),
  new Language('hno', 'Northern Hindko', 'ہندکو'),
  new Language('sag', 'Sango', 'Sängö'),
  new Language('mey', 'Hassaniyya', 'حسانية'),
  new Language('ayh', 'Hadrami Arabic', 'حضرمي'),
  new Language('lmn', 'Lambadi', 'బంజార'),
  new Language('sid', 'Sidamo', 'Sidaamu Afoo'),
  new Language('gpe', 'Ghanaian Pidgin English', 'Pidgin'),
  new Language('bew', 'Betawi', 'Betawi'),
  new Language('lir', 'Liberian Pidgin English', 'Koloqua'),
  new Language('aln', 'Gheg Albanian', 'Gegnisht'),
  new Language('min', 'Minangkabau', 'Minangkabau'),
  new Language('fuf', 'Pular', 'Pular'),
  new Language('tat', 'Tatar', 'татар теле'),
  new Language('awa', 'Awadhi', 'अवधी'),
  new Language('ssw', 'Swati', 'siSwati'),
  new Language('scn', 'Sicillian', 'Sicilianu'),
  new Language('shn', 'Shan', 'လိၵ်ႈတႆး‎'),
  new Language('uzs', 'Southern Uzbek', 'ﯣزبېک'),
  new Language('tiv', 'Tiv', 'Tiv'),
  new Language('sou', 'Southern Thai', 'ภาษาไทยถิ่นใต้'),
  new Language('lao', 'Lao', 'ພາສາລາວ‎'),
  new Language('bug', 'Bugis', 'Basa Ugi'),
  new Language('sdh', 'Southern Kurdish', 'کوردیی باشووری'),
  new Language('mtr', 'Mewari', 'मेवाड़ी'),
];
